dist: bionic
sudo: required
language: elixir

elixir: 1.12.1
otp_release: 24.0

addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.4.0-rc0.tgz
  - mkdir ${PWD}/mongodb
  - tar xzf mongodb-linux-x86_64-ubuntu1804-4.4.0-rc0.tgz --strip-components=1 -C ${PWD}/mongodb

before_script:
  - pyenv global 3.6
  - pip3 install --upgrade pip
  - pip3 install mtools[all]
  - export PATH=${PWD}/mongodb/bin/:$PATH
  - mlaunch init --setParameter enableTestCommands=1 --replicaset --name "rs_1"

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix coveralls.travis
